BulkyBookWeb/Areas/Admin/Controllers/CompanyController.cs
using BulkyBook.Data;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using BulkyBook.Models.ViewModels;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NuGet.Protocol;

namespace BulkyBookWeb.Areas.Admin.Controllers
{ 
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]

    public class CompanyController : Controller
    {
        private readonly IUnitofWork _unitOfWork;
       

        public CompanyController(IUnitofWork unitOfWork, IWebHostEnvironment hostEnvironment)
        {
            _unitOfWork = unitOfWork;
            
         }



        public IActionResult Index()
        {
           // IEnumerable<CoverType> objCoverTypeList = _unitOfWork.CoverType.GetAll();
            return View();
        }

       
        public IActionResult Upsert(int? id)
        {
          
            Company company = new();
            

            if (id == null || id == 0)
            {
                
                return View(company);
            }
            else 
            {

                
                company  = _unitOfWork.Company.GetFirstOrDefault(u => u.Id == id);
                return View(company);

            }
           
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Company obj)
        {
            if (ModelState.IsValid)
            {

               
                if(obj.Id==0)
                {

                    _unitOfWork.Company.Add(obj);
                    TempData["success"] = "Company Created Successfully";

                }
                else
                {
                    _unitOfWork.Company.Update(obj);
                    TempData["success"] = "Company Updated Successfully";

                }
                _unitOfWork.Save();
              
               

                return RedirectToAction("Index");
            }
            return View(obj);
        }





        #region API CALLS

        [HttpGet]
        public IActionResult GetAll()
        {
            var companyList = _unitOfWork.Company.GetAll();
            return Json(new { data = companyList });
        }

        [HttpDelete]

        public IActionResult Delete(int? id)
        {
            var obj = _unitOfWork.Company.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return Json(new { success = false, message = "Error while Deleting" });
            }



            _unitOfWork.Company.Remove(obj);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Delete Successuful" });



        }

        #endregion


    }
}

BulkyBookWeb/Areas/Admin/Controllers/CoverTypeController.cs
using BulkyBook.Data;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NuGet.Protocol;

namespace BulkyBookWeb.Areas.Admin.Controllers
{ 
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]

    public class CoverTypeController : Controller
    {
        private readonly IUnitofWork _unitOfWork;

        public CoverTypeController(IUnitofWork unitOfWork)
        {
            _unitOfWork = unitOfWork;

        }



        public IActionResult Index()
        {
            IEnumerable<CoverType> objCoverTypeList = _unitOfWork.CoverType.GetAll();
            return View(objCoverTypeList);
        }

         
        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public IActionResult Create(CoverType obj)
        {
           
          


            if (ModelState.IsValid)
            {
                _unitOfWork.CoverType.Add(obj);
                _unitOfWork.Save();
                TempData["success"] = "CoverType Created Successfully";

                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
           

            var CoverTypeFromDbFirst = _unitOfWork.CoverType.GetFirstOrDefault(u => u.Id == id);

            if (CoverTypeFromDbFirst == null)
            {
                return NotFound();
            }

            return View(CoverTypeFromDbFirst);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CoverType obj)
        {


            if (ModelState.IsValid)
            {
                _unitOfWork.CoverType.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "CoverType Updated Successfully";

                return RedirectToAction("Index");
            }
            return View(obj);
        }
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
           

            var CoverTypeFromDbFirst = _unitOfWork.CoverType.GetFirstOrDefault(u => u.Id == id);

            if (CoverTypeFromDbFirst == null)
            {
                return NotFound();
            }

            return View(CoverTypeFromDbFirst);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var CoverTypeFromDbFirst = _unitOfWork.CoverType.GetFirstOrDefault(u => u.Id == id);
            if (CoverTypeFromDbFirst == null)
            {
                return NotFound();
            }


            _unitOfWork.CoverType.Remove(CoverTypeFromDbFirst);
            _unitOfWork.Save();
            TempData["success"] = "CoverType Deleted Successfully";


            return RedirectToAction("Index");

        }




    }
}

BulkyBookWeb/Areas/Admin/Views/Company/Index.cshtml
<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6 ">
            <h2 class="text-primary">
                Company List
            </h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Company" asp-action="Upsert" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i>  Create New Company
            </a>
        </div>

    </div>

</div>
<br />
<br />

<table id="tblData" class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
         <th>Name</th>
         <th>Address</th>
         <th>City</th>
         <th>State</th>
         <th>Phone Number</th>
         <th></th>
        
        </tr>
    </thead>
  @*  <tbody>

        @foreach (var obj in Model)
        {
            <tr>
                <td width="50%">
                    @obj.Name
                </td>

                <td>
                    <div class="m-75 btn-group" role="group">
                        <a asp-controller="CoverType" asp-action="Edit" asp-route-id="@obj.Id"
                       class="btn btn-primary mx-2"> <i class="bi bi-pencil-square"></i>Edit</a>

                        <a asp-controller="CoverType" asp-action="Delete" asp-route-id="@obj.Id"
                       class="btn btn-danger mx-2"> <i class="bi bi-trash"></i>Delete</a>
                    </div>

                </td>
            </tr>
        }
    </tbody>*@
</table>




<br />
<br />

@section Scripts{
    <script src="~/js/company.js"></script>
}

BulkyBookWeb/Areas/Admin/Views/Company/Upsert.cshtml
@model BulkyBook.Models.Company

<form method="post" asp-action="Upsert" enctype="multipart/form-data" class="mb-5">
    <input asp-for="Id" hidden />
    

    <div class="row">
        <div class="col-10">
            <div class="border p-3 mt-4  row">
                <div class="col-12 pb-2">
                    <h2 class="text-primary">
                        @(Model.Id != 0 ? "Update" : "Create") Company
                    </h2>
                    <hr />
                </div>

                @*        <div asp-validation-summary="All"></div>     *@
                <div class="mb-3 ">
                    <label asp-for="Name"> </label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"> </span>
                </div>
                <div class="mb-3 ">
                    <label asp-for="PhoneNumber"> </label>
                    <input asp-for="PhoneNumber" class="form-control" />
                    <span asp-validation-for="PhoneNumber" class="text-danger"> </span>
                </div>
                 <div class="mb-3 ">
                    <label asp-for="StreetAddress"> </label>
                    <input asp-for="StreetAddress" class="form-control" />
                    <span asp-validation-for="StreetAddress" class="text-danger"> </span>
                </div>
                <div class="mb-3 ">
                    <label asp-for="City"> </label>
                    <input asp-for="City" class="form-control" />
                    <span asp-validation-for="City" class="text-danger"> </span>
                </div>
                <div class="mb-3 ">
                    <label asp-for="State"> </label>
                    <input asp-for="State" class="form-control" />
                    <span asp-validation-for="State" class="text-danger"> </span>
                </div>
                <div class="mb-3 ">
                    <label asp-for="PostalCode"> </label>
                    <input asp-for="PostalCode" class="form-control" />
                    <span asp-validation-for="PostalCode" class="text-danger"> </span>
                </div>




                <div class="col-12">
                    @if (Model.Id != 0)
                    {
                        <button type="submit" class="btn btn-primary" style="width:150px">
                            Update
                        </button>
                    }
                    else
                    {
                        <button type="submit"  class="btn btn-primary" style="width:150px">
                            Create
                        </button>
                    }

                    <a asp-controller="Company" asp-action="Index" class="btn btn-secondary" style="width:150px">Back to the list </a>
                </div>
            </div>
        </div>

       

    </div>

   
</form>

<br />
<br />



@section Scripts{
  @{
      <partial name="_ValidationScriptsPartial"/>
  }
   
    }